#!/usr/bin/env python3

# ------------------------------------------------------------------------
import panflute as pf

# ------------------------------------------------------------------------
TEMPLATE = r'''
<textarea id="{name}">{contents}</textarea>
<script>$(function() {{ ecmodule.createECEditor(document.getElementById("{name}")); }})</script>
'''.lstrip()

# ------------------------------------------------------------------------
COUNTER = 0

# ------------------------------------------------------------------------
def dynamic_easycrypt(options, data, element, doc):
  global COUNTER

  if doc.format not in ['html', 'html5']:
     return

  if isinstance(options, str):
     contents = options
  else:
    with open(options['filename'], 'r') as stream:
        contents = stream.read()

  contents = contents.rstrip()

  COUNTER += 1
  data = dict(contents = contents, name = f'ec-{COUNTER}')

  return pf.elements.RawBlock(TEMPLATE.format(**data))

# ------------------------------------------------------------------------
def main(doc = None):
    return pf.run_filter(
      pf.yaml_filter,
      tag = 'ecblock',
      strict_yaml = False,
      function = dynamic_easycrypt,
      doc = doc
    )

# ------------------------------------------------------------------------
if __name__ == "__main__":
  main()
